package bigdata.filesystem.comn.base;

public enum BaseMessage {
    SUCCESS("000"),
    //异常
    EXCEPTION("111"),
    DATA_ERROR("数据异常！"),
    VALID_CODE_ERROR("验证码错误!"),
    REQUEST_EMPTY("请求参数缺失！"),
    NO_MESSAGE("报错信息未定义"),
    TEST_CREATE_SUCCESSS("TEST创建成功"),
    LOGIN_SUCCESS("登录成功"),
    TEST_IS_NULL("TestDTO为空"),
    USERNAME_OCCUPIED("用户名已被使用"),
    PLEASE_LOGIN("请登录！"),
    USER_OR_PWD_ERROR("用户名或者密码错误！"),
    FILE_EMPTY("文件为空"),
    FILE_NAME_EMPTY("文件名为空！"),
    FILE_TOO_LARGE("文件太大！"),
    FILE_EXISTS("文件已经存在！"),
    FILE_IO_EXP("文件读写异常！"),
    FILE_UPLOAD_ERR("文件上传失败！"),
    FILE_MISS_CHUNKS("文件部分模块上传错误！"),
    TEMP_FILE_QUERY_MD5_SUCCESS("MD5查询成功"),
    USER_IS_NULL("UserDTO为空"),
    USER_CREATE_SUCCESSS("USER创建成功"),
    ROLE_IS_NULL("RoleDTO为空"),
    ROLE_CREATE_SUCCESSS("Role创建成功"),
    ROLE_NAME_DUPLICATE("该角色名已存在"),
    UPDATE_USER_SUCCESS("User更新成功"),
    SMALLFILE_UPLOAD_SUCCESS("上传小文件成功"),
    LARGEFILE_UPLOAD_SUCCESS("上传大文件成功"),
    FREEZE_USER_SUCCESS("冻结用户成功"),
    UNFREEZE_USER_SUCCESS("解冻用户成功"),
    USER_NOEXIST("用户不存在"),
    USER_FREEZED("用户被冻结！"),
    FILE_TYPE_ERROR("文件类型错误！"),
    FILE_NOT_EXIST("文件不存在！"),
    NO_CAN_ACCESS_FILE("没有可以访问的文件！"),
    FILE_DELETED("文件已删除！"),
    ROLE_UPDATE_SUCCESS("角色更新成功！"),
    FREEZE_ROLE_SUCCESS("冻结角色成功!"),
    UNFREEZE_ROLE_SUCCESS("解冻角色成功！"),
    ROLE_NOT_EXIST("角色不存在"),
    PWD_ERROR("密码错误！"),
    PWD_NOT_CHANGE("密码与旧密码相同！"),
    DELETE_ROLE_SUCCESS("删除角色成功！"),
    DELETE_USER_SUCCESS("删除用户成功！"),
    PWD_CHANGE_SUCCESS("密码修改成功"),
    RIGHT_CREATE_SUCCESS("创建权限成功!"),
    RIGHT_IS_NULL("权限为空!"),
    DONT_HAVE_RIGHT("没有相关权限！"),
    RIGHT_TYPE_IS_NULL("权限类型为空!"),
    RIGHT_NAME_DUPLICATE("权限名重复"),
    RIGHT_UPDATE_SUCCESS("更新权限成功!"),
    RIGHT_DELETE_SUCCESS("更新删除成功!"),
    BIND_NOT_EXIST("绑定不存在"),
    ROLE_BIND_SUCCESS("角色绑定成功"),
    ROLE_UNBIND_SUCCESS("角色解绑成功"),
    ROLE_RIGHT_BIND_SUCCESS("角色绑定权限成功！"),
    ROLE_RIGHT_UNBIND_SUCCESS("角色绑定权限成功！"),
    CATALOG_CREATE_SUCCESS("创建目录成功!"),
    CATALOG_UPDATE_SUCCESS("更新目录成功!"),
    CATALOG_FREEZE_SUCCESS("冻结目录成功!"),
    CATALOG_NOT_NORMAL("目录状态非正常!"),
    UNFREEZE_CATALOG_SUCCESS("解冻目录成功!"),
    CATALOG_DELETE_SUCCESS("删除目录成功!"),
    CATALOG_IS_NULL("目录不存在"),
    CATALOG_IS_DELETED("目录已经被删除！"),
    CATALOG_NAME_DUPLICATE("目录名重复"),
    USER_RIGHT_DUPLICATE("用户权限绑定重复"),
    USER_CATALOG_RIGHT_EXISTED("用户目录权限已存在!"),
    USER_CATALOG_RIGHT_NOT_EXISTED("用户目录权限不存在!"),
    USER_CATALOG_RIGHT_UNBIND_SUCCESS("用户目录权限解绑成功!"),
    USER_CATALOG_RIGHT_BIND_SUCCESS("用户目录权限绑定成功!"),
    FILE_UPLOAD_SUCCESS("文件上传成功！"),
    ROLE_IS_DELETED("角色已经被删除！"),
    USER_IS_DELETED("用户已经被删除！"),
    PWD_DTO_IS_NULL("pwdDTO为空"),
    FILE_DTO_IS_NULL("fileDTO为空"),
    FILE_IS_SMALL("文件是小文件！"),
    BIND_DUPLICATE("绑定关系已经存在！"),
    FILE_FREEZE_SUCCESS("文件冻结成功"),
    FILE_UNFREEZE_SUCCESS("文件解冻成功"),
    FILE_DELETE_SUCCESS("文件删除成功"),
    FILE_UPDATE_SUCCESS("文件更新成功"),
    FILE_DOWNLOAD_SUCCESS("文件下载成功"),
    PDF2DOCX_SUCCESS("PDF转换为DOCX成功"),
    PDF2DOCX_FAILED_NO_PDF("PDF转换为DOCX失败：没有可解析数据"),
    PDF2DOCX_FAILED_IS_NOT_PDF("PDF转换为DOCX失败：文件不是PDF"),
    USER_FILE_RIGHT_BIND_SUCCESS("用户绑定文件权限成功"),
    USER_FILE_RIGHT_UNBIND_SUCCESS("用户解绑文件权限成功"),
    ROLE_ALREADY_BIND_RIGHT("角色已绑定权限"),
    CATALOG_NAME_ILLEGAL("目录名不合法"),
    CATALOG_NAME_NOT_CHANGED("目录名未改变"),
    PARENT_CATALOG_NOT_EXISTS("父目录不存在"),
    USER_RIGHT_BIND_SUCCESS("用户绑定权限成功"),
    USER_RIGHT_UNBIND_SUCCESS("用户解绑权限成功"),
    USER_ROLE_UNBIND_SUCCESS("用户解绑角色成功"),
    USER_ROLE_BIND_SUCCESS("用户绑定角色成功"),
    GET_DATA_SUCCESS("数据查询成功"),
    DTO_NOT_EXIST("DTO不存在"),
    SUCCESS_GET_ALL("成功获取所有数据"),
    DELETE_RIGHT_SUCCESS("删除权限成功"),
    DELETE_PARSE_DOC_FAILED("删除解析文档失败！"),
    COMPLETE_PATH_NOT_EXIST("完整路径不存在！"),
    PARENT_COMPLETE_PATH_NOT_EXIST("父级完整路径不存在！"),
    TESSERACT_INIT_ERROR("Tesseract 初始化失败！"),
    TESSERACT_PARSE_ERROR("Tesseract 解析失败！"),
    TIKA_PARSE_ERROR("Tika 解析失败！"),
    ES_DEL_INDEX_ERROR("删除索引失败！"),
    ES_CHECK_INDEX_ERROR("索引检测失败！"),
    ES_CHECK_ID_ERROR("ES ID获取失败！"),
    ES_SAVE_SINGLE_DATA_ERROR("ES存储单条数据失败！"),
    ES_SEARCH_ERROR("ES查询失败！"),
    ES_SAVE_BULK_DATA_ERROR("ES存储批量数据失败！"),
    ES_DELETE_ERROR("ES删除失败！"),
    ES_UPDATE_ERROR("ES更新失败！"),
    ES_CREATE_ERROR("ES创建失败！"),
    ES_XContentBuilder_ERROR("XContentBuilder构建失败！"),
    ES_JSON_PARSE_ERROR("ES Json解析异常！"),
    LOG_UNFREEZE_SUCCESS("日志恢复成功"),
    LOG_DELETE_SUCCESS("日志删除成功"),
    AUTO_TABLE_NAME_EXISTED("表名已经存在"),
    AUTO_NOT_EXISTED("自动填表数据不存在"),
    AUTO_CREATE_SUCCESS("创建自动填表数据成功!"),
    AUTO_UPDATE_SUCCESS("更新自动填表数据成功!"),
    AUTO_DELETE_SUCCESS("删除自动填表数据成功!"),
    EXCEL_PARSE_ERROR("Excel解析异常！"),
    WORD2HTML_SUCCESS("Word转HTML成功！"),
    WORD2HTML_FAILED("Word转HTML失败！"),
    HTML2WORD_SUCCESS("HTML转Word成功！"),
    HTML2WORD_FAILED("HTML转Word失败！"),
    ;
    private final String msg;

    BaseMessage(final String msg) {
        this.msg = msg;
    }

    public String getMsg() {
        return msg;
    }

    @Override
    public String toString() {
        return "[" + getMsg() + "]";
    }
}
